### ISSUE TITLE
마지막 버튼 구현안

### ISSUE THREAD

**Issue by vesselofgod** [osamhack2020/APP_LOCKA_DreamY#22]
1. 전투휴무/공휴일 기능
2. D-day와 월급계산기 분리
3. 앱 삭제기능
4. ect..

**Comment by 7dudtj** [comment]
개인적으로는 1번이 제일 좋을것 같기는 하나 2번 3번도 괜찮은 대안이 될 수 도 있을 것 같음

**Comment by vesselofgod** [comment]
전투휴무/공휴일 기능으로 구현 완료
